- id: doi:10.1016/j.ufug.2025.128797
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1618866725001311-gr6.jpg
- id: doi:10.36574/jpp.v8i3.634
- id: doi:10.1080/02697459.2024.2342756
  image: https://www.tandfonline.com/cms/asset/c6f93568-a948-4d2e-b6e2-f53ff8c0929c/cppr_a_2342756_f0006_oc.jpg
- id: doi:10.31327/gsej.v3i2.1704
  authors: 
  - Luthfi Muhamad Iqbal
  - Alvaryan Maulana
  image: 
- id: doi:10.47266/bwp.v3i2.78
  authors: Luthfi Muhamad Iqbal
- id: doi:10.26182/5cca430b16437
- id: https://journals.itb.ac.id/index.php/jpwk/article/view/4164
  title: The Emergence of Jakarta-Bandung Mega-Urban Region and Its Future Challenges
  authors: Agung Mahesa Himawan Dorodjatoen
  date: 2009-04-01
  publisher: Journal of Regional and City Planning
  link: https://journals.itb.ac.id/index.php/jpwk/article/view/4164
  
